services:
    app.admin.g_list:
        class: Builder\ListBundle\Admin\G_ListAdmin
        arguments: [~, Builder\ListBundle\Entity\G_List, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Métier", label: "Listes" }
        public: true

    app.admin.g_listitem:
        class: Builder\ListBundle\Admin\G_ListItemAdmin
        arguments: [~, Builder\ListBundle\Entity\G_ListItem, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false, group: 'Métier' }
        public: true
